---
apiVersion: v1
kind: Deployment
metadata:
  name: deploy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - image: 285328526676.dkr.ecr.us-east-1.amazonaws.com/ashwiin11:latest
          name: javaApp
          imagePullPolicy: always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  port:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app:  demo-app
  type: LoadBalancer